version: '3.9'
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
      target: database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=todos
      - TZ=Asia/Tokyo
    restart: always
volumes:
  pgdata: